### ISSUE TITLE
00_Prepration-- 00_jund_downloads.ipynb

### ISSUE THREAD

**Issue by starboyvarun** [wkopp/janggu_usecases#2]
Above all modules run of 00_jund_downloads.ipynb.
but These two are giving the error.
![2](https://user-images.githubusercontent.com/26819449/129888286-37a0b2b2-c30b-4d21-ae19-1f0f09c5fa33.JPG)

![3](https://user-images.githubusercontent.com/26819449/129888294-37725c9f-5a90-4c67-9787-7f31c6d0697a.JPG)
 
 Can you tell me how should I fix it?

**Comment by wkopp** [comment]
Hi @starboyvarun ,

you need to install samtools and bedtools. If you are using conda you can install these tools via `conda install -c bioconda samtools bedtools` in the environment in which you want to run the code.

Best,
Wolfgang

**Comment by starboyvarun** [comment]
Hello @wkopp 
I am using Google collab. I installed all library still it's giving this bug.
Can you send me your email? 
I can show you my code.

**Comment by wkopp** [comment]
I see. samtools and bedtools are stand-alone tools rather than python libraries, so they cannot be installed via pip. I suppose that is the issue. They are sort of system requirements. I'm not sure how install to system requirements in google collab. Did you try to install the tools via `apt install`, perhaps?

**Comment by starboyvarun** [comment]
![4](https://user-images.githubusercontent.com/26819449/130009832-9b43151d-680d-4146-b60a-6615e66cecf9.JPG)
![5](https://user-images.githubusercontent.com/26819449/130009837-a44d2ca9-f042-4103-91c0-8a26f17584a0.JPG)
![6](https://user-images.githubusercontent.com/26819449/130009841-cb655b9e-0271-4503-8a7b-853c7620f5bc.JPG)

 I cloned all repositories, Still, it was giving errors.

**Comment by starboyvarun** [comment]
I am able to solve all the previous issues thankyou, @wkopp.
